Repository eclipse-zenoh/zenoh-backend-s3, pull requests merged in 2024-09, with the labels that each got.

#162 spawn task in plugin runtime if dynamic plugin
  src/lib.rs
Labels: bug

#164 Align Config example with other storages
  EXAMPLE_CONFIG.json5
  README.md
Labels: documentation

#173 Update zenoh
  Cargo.lock
Labels: internal

#174 Update zenoh
  Cargo.lock
Labels: internal

#183 Fix sync lock
  Cargo.lock
  src/lib.rs
Labels: internal

#189 chore: update release.yml for required labels
  .github/release.yml
Labels: internal
